In [26]:
import torch
import torch.nn as nn
import torch.optim as optim

from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [27]:
#device configuration
#check for cuda availability

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

In [28]:
print(device)

cuda


In [29]:
#data collection and preprocessing

In [30]:
data = load_breast_cancer()
x = data.data
y = data.target

In [31]:
print(x)

[[1.799e+01 1.038e+01 1.228e+02 ... 2.654e-01 4.601e-01 1.189e-01]
 [2.057e+01 1.777e+01 1.329e+02 ... 1.860e-01 2.750e-01 8.902e-02]
 [1.969e+01 2.125e+01 1.300e+02 ... 2.430e-01 3.613e-01 8.758e-02]
 ...
 [1.660e+01 2.808e+01 1.083e+02 ... 1.418e-01 2.218e-01 7.820e-02]
 [2.060e+01 2.933e+01 1.401e+02 ... 2.650e-01 4.087e-01 1.240e-01]
 [7.760e+00 2.454e+01 4.792e+01 ... 0.000e+00 2.871e-01 7.039e-02]]


In [32]:
print(y)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 1 0 0 0 0 0 0 0 0 1 0 1 1 1 1 1 0 0 1 0 0 1 1 1 1 0 1 0 0 1 1 1 1 0 1 0 0
 1 0 1 0 0 1 1 1 0 0 1 0 0 0 1 1 1 0 1 1 0 0 1 1 1 0 0 1 1 1 1 0 1 1 0 1 1
 1 1 1 1 1 1 0 0 0 1 0 0 1 1 1 0 0 1 0 1 0 0 1 0 0 1 1 0 1 1 0 1 1 1 1 0 1
 1 1 1 1 1 1 1 1 0 1 1 1 1 0 0 1 0 1 1 0 0 1 1 0 0 1 1 1 1 0 1 1 0 0 0 1 0
 1 0 1 1 1 0 1 1 0 0 1 0 0 0 0 1 0 0 0 1 0 1 0 1 1 0 1 0 0 0 0 1 1 0 0 1 1
 1 0 1 1 1 1 1 0 0 1 1 0 1 1 0 0 1 0 1 1 1 1 0 1 1 1 1 1 0 1 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 1 1 1 1 1 1 0 1 0 1 1 0 1 1 0 1 0 0 1 1 1 1 1 1 1 1 1 1 1 1
 1 0 1 1 0 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 0 1 0 1 1 1 1 0 0 0 1 1
 1 1 0 1 0 1 0 1 1 1 0 1 1 1 1 1 1 1 0 0 0 1 1 1 1 1 1 1 1 1 1 1 0 0 1 0 0
 0 1 0 0 1 1 1 1 1 0 1 1 1 1 1 0 1 1 1 0 1 1 0 0 1 1 1 1 1 1 0 1 1 1 1 1 1
 1 0 1 1 1 1 1 0 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 0 1 0 0 1 0 1 1 1 1 1 0 1 1
 0 1 0 1 1 0 1 0 1 1 1 1 1 1 1 1 0 0 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 0 1
 1 1 1 1 1 1 0 1 0 1 1 0 

In [33]:
x.shape


(569, 30)

In [34]:
y.shape

(569,)

In [35]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [36]:
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [37]:
print(x_train)

[[-1.44075296 -0.43531947 -1.36208497 ...  0.9320124   2.09724217
   1.88645014]
 [ 1.97409619  1.73302577  2.09167167 ...  2.6989469   1.89116053
   2.49783848]
 [-1.39998202 -1.24962228 -1.34520926 ... -0.97023893  0.59760192
   0.0578942 ]
 ...
 [ 0.04880192 -0.55500086 -0.06512547 ... -1.23903365 -0.70863864
  -1.27145475]
 [-0.03896885  0.10207345 -0.03137406 ...  1.05001236  0.43432185
   1.21336207]
 [-0.54860557  0.31327591 -0.60350155 ... -0.61102866 -0.3345212
  -0.84628745]]


In [38]:
print(x_test)

[[-0.46649743 -0.13728933 -0.44421138 ... -0.19435087  0.17275669
   0.20372995]
 [ 1.36536344  0.49866473  1.30551088 ...  0.99177862 -0.561211
  -1.00838949]
 [ 0.38006578  0.06921974  0.40410139 ...  0.57035018 -0.10783139
  -0.20629287]
 ...
 [-0.73547237 -0.99852603 -0.74138839 ... -0.27741059 -0.3820785
  -0.32408328]
 [ 0.02898271  2.0334026   0.0274851  ... -0.49027026 -1.60905688
  -0.33137507]
 [ 1.87216885  2.80077153  1.80354992 ...  0.7925579  -0.05868885
  -0.09467243]]


In [39]:
type(x_train)

numpy.ndarray

In [40]:
#convert data to pytorch tensor

In [41]:
x_train = torch.tensor(x_train,dtype = torch.float32).to(device)
x_test = torch.tensor(x_test,dtype = torch.float32).to(device)
y_train = torch.tensor(y_train,dtype = torch.float32).to(device)
y_test = torch.tensor(y_test,dtype = torch.float32).to(device)

In [42]:
#nn in pytorch ... is different ... nn architecture ..  it just a simple ann

In [52]:
class NeuralNet(nn.Module):
    def __init__(self, input_size, hidden_size, output_size):
        super().__init__()
        self.fc1 = nn.Linear(input_size, hidden_size)
        self.relu = nn.ReLU()
        self.fc2 = nn.Linear(hidden_size, output_size)
        self.sigmoid = nn.Sigmoid()

    def forward(self, x):
        out = self.fc1(x)
        out = self.relu(out)
        out = self.fc2(out)
        out = self.sigmoid(out)
        return out


In [57]:
input_size = x_train.shape[1]
hidden_size = 64
output_size = 1
learning_rate = 0.001
num_of_epochs = 100

In [58]:
model = NeuralNet(input_size,hidden_size,output_size).to(device)

In [59]:
criterion = nn.BCELoss()
optimizer  = optim.Adam(model.parameters(),lr = learning_rate)

In [61]:
for epoch in range(num_of_epochs):
    model.train()
    optimizer.zero_grad()
    outputs = model(x_train)

    loss = criterion(outputs, y_train.view(-1, 1))

    loss.backward()
    optimizer.step()

    with torch.no_grad():
        predicted = outputs.round()
        correct = (predicted == y_train.view(-1, 1)).float().sum()
        accuracy = correct / y_train.size(0)

    if (epoch + 1) % 10 == 0:
        print(f"Epoch {epoch+1}/{num_of_epochs} - Loss: {loss.item():.4f} - Accuracy: {accuracy.item() * 100:.2f}%")


Epoch 10/100 - Loss: 0.5772 - Accuracy: 87.25%
Epoch 20/100 - Loss: 0.4614 - Accuracy: 91.65%
Epoch 30/100 - Loss: 0.3673 - Accuracy: 92.09%
Epoch 40/100 - Loss: 0.2936 - Accuracy: 93.41%
Epoch 50/100 - Loss: 0.2389 - Accuracy: 94.73%
Epoch 60/100 - Loss: 0.1995 - Accuracy: 95.38%
Epoch 70/100 - Loss: 0.1709 - Accuracy: 96.04%
Epoch 80/100 - Loss: 0.1497 - Accuracy: 96.48%
Epoch 90/100 - Loss: 0.1335 - Accuracy: 96.70%
Epoch 100/100 - Loss: 0.1208 - Accuracy: 96.92%


In [63]:
#evaluation
model.eval()
with torch.no_grad():
    outputs = model(x_test)
    predicted = outputs.round()
    correct = (predicted == y_test.view(-1, 1)).float().sum()
    accuracy = correct / y_test.size(0)
    print(f"Test Accuracy: {accuracy.item() * 100:.2f}%")


Test Accuracy: 98.25%


In [64]:
#evaluation
model.eval()
with torch.no_grad():
    outputs = model(x_train)
    predicted = outputs.round()
    correct = (predicted == y_train.view(-1, 1)).float().sum()
    accuracy = correct / y_train.size(0)
    print(f"Test Accuracy: {accuracy.item() * 100:.2f}%")

Test Accuracy: 96.92%
